import Vue from "vue";
import { ExternalLink, ClassDirective, LoadableButton } from 'bee-vue-gang';
import CompanyAutocomplete from "src/components/CompanyAutocomplete";
import BeeSubheader from "src/components/BeeSubheader";
import GraphDisplay from "src/components/GraphDisplay";
import FeedbackForm from "src/components/FeedbackForm";
import DualNav from "src/components/DualNav";
import BeeIssue from "src/components/BeeIssue";
import BeeTopIssue from "src/components/BeeTopIssue";
import BeeCompany from "src/components/BeeCompany";
import PotentiallyBigList from "src/components/PotentiallyBigList";
Vue.component("BeeCompany", BeeCompany);
Vue.component("BeeIssue", BeeIssue);
Vue.component("BeeTopIssue", BeeTopIssue);
Vue.component("BeeSubheader", BeeSubheader);
//Vue.component("Loader", Loader);
Vue.component("LoadableButton", LoadableButton);
Vue.component("GraphDisplay", GraphDisplay);
Vue.component("PotentiallyBigList", PotentiallyBigList);
Vue.component("FeedbackForm", FeedbackForm);
Vue.component("CompanyAutocomplete", CompanyAutocomplete);
Vue.component("DualNav", DualNav);
Vue.component("ax", ExternalLink);
Vue.directive("class", ClassDirective);